image: openjdk:8u121-jdk-alpine

stages:
  - test
  - build
  - docker

test:
  stage: test
  before_script:
    - apk update
    - apk add mvn
  script:
   - mvn verify


build:
  stage: build
  only:
    - master
  before_script:
    - apk update
    - apk add maven
  script:
    - mvn package


docker:
  image: docker:latest
  variables:
    REPOSITORY_URL: ec2-18-184-48-57.eu-central-1.compute.amazonaws.com/twitteranalyzer-core
  stage: docker
  services:
    - docker:dind
  only:
    - master
  before_script:
    - apk add --no-cache curl jq python py-pip
    - pip install awscli

  tags:
    - docker
  script:
    - $(aws ecr get-login --no-include-email --region eu-central-1)
    - docker build -t $REPOSITORY_URL .
    - docker push $REPOSITORY_URL

