spring:
  profiles:
      active: "dev"

---

spring:
  profiles: dev
  session:
    store-type: redis
  redis:
    host: localhost
    password: 1234
    port: 6379

logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG

server:
  port: 3001

twitter:
  api-key: gYBOmrWOnlS69DScInBWrTGFr
  api-secret: wv8LHjQnCUjR28ALBVinPFRIiufvCQoh82qvmCo2ufkioZVFkU
  access-token: 964455826084777984-OxlNnBZYownQAwRAa57c61UApqsYUJ3
  access-token-secret: frUPdfMpefBgWrwGOFn292o4emhUdYg31gpTy9PijLldW

---
