spring:
  profiles:
      active: "dev"

---

spring:
  profiles: dev

allowedorigins:
  url: http://localhost:3000

twitter:
  api-key: ON3A0745DdbWgGoSwLNDnwEHn
  api-secret: 8sr6ounIl6ipoEs2Z4TWrB2VWoLoo1AIm26ejfuyatnX88TDIh
  access-token: 964455826084777984-BQd5TXqsc0YfqdZw1nzwMPUwcXfbQbm
  access-token-secret: dLSHiez76YzrW447jcgXYHtytRyJBI00MBUizOO4tqM0p

googlemaps:
  api-key: AIzaSyDnXHmMF1dTcCwHf5owel10aP1gaKw0ImE
  url: https://maps.googleapis.com/maps/api/geocode/json

yahoo:
  url: https://query.yahooapis.com/v1/public/yql

locationiq:
  api-key: c38eb33100ed51
  url: https://eu1.locationiq.com/v1/reverse.php




---

spring:
  profiles: prod

allowedorigins:
  url: "*"

twitter:
  api-key: ON3A0745DdbWgGoSwLNDnwEHn
  api-secret: 8sr6ounIl6ipoEs2Z4TWrB2VWoLoo1AIm26ejfuyatnX88TDIh
  access-token: 964455826084777984-BQd5TXqsc0YfqdZw1nzwMPUwcXfbQbm
  access-token-secret: dLSHiez76YzrW447jcgXYHtytRyJBI00MBUizOO4tqM0p

googlemaps:
  api-key: AIzaSyDnXHmMF1dTcCwHf5owel10aP1gaKw0ImE
  url: https://maps.googleapis.com/maps/api/geocode/json

yahoo:
  url: https://query.yahooapis.com/v1/public/yql

locationiq:
  api-key: c38eb33100ed51
  url: https://eu1.locationiq.com/v1/reverse.php

---


